import { NavItem, Language } from '@/src/types/navbar.types';

export const navItems: NavItem[] = [
  {
    label: "nav.weightLoss",
    fallback: "Weight Loss",
    href: "/weight-loss/",
    submenu: {
      weightLoss: {
        items: [
          { key: "submenu.weightLoss.ozempic", fallback: "ozempic-malaysia" },
          { key: "submenu.weightLoss.wegovy", fallback: "wegovy-malaysia" },
          { key: "submenu.weightLoss.mounjaro", fallback: "mounjaro-malaysia" },
          { key: "submenu.weightLoss.duromine", fallback: "duromine-malaysia" },
          { key: "submenu.weightLoss.doctorMonitored", fallback: "doctor-monitored-weight-loss-malaysia" },
          { key: "submenu.weightLoss.hcgWeightLoss", fallback: "hcg-programme-malaysia" },
          { key: "submenu.weightLoss.fatFreezing", fallback: "fat-freezing-malaysia" },
          { key: "submenu.weightLoss.coolSculpting", fallback: "coolsculpting-malaysia" },
          { key: "submenu.weightLoss.glp1", fallback: "glp-1-programme-malaysia" },
          { key: "submenu.weightLoss.zepbound", fallback: "zepbound-malaysia" },
          { key: "submenu.weightLoss.ivDrips", fallback: "iv-drip-malaysia" },
        ],
      },
    },
  },
  {
    label: "nav.aestheticTreatments",
    fallback: "Aesthetic Treatments",
    href: "#",
    submenu: {
      skin: {
        label: "categories.skin",
        fallback: "Skin",
        items: [
          { key: "submenu.skin.acneTreatment", fallback: "acne-treatment-malaysia" },
          { key: "submenu.skin.acneScar", fallback: "acne-scar-treatment-malaysia" },
          { key: "submenu.skin.melasma", fallback: "melasma-treatment-malaysia" },
          { key: "submenu.skin.moleRemoval", fallback: "mole-removal-malaysia" },
          { key: "submenu.skin.hydrafacial", fallback: "hydrafacial-malaysia" },
          { key: "submenu.skin.picoLaser", fallback: "pico-laser-malaysia" },
          { key: "submenu.skin.darkCircle", fallback: "dark-eye-circle-treatment-malaysia" },
          { key: "submenu.skin.whitening", fallback: "skin-whitening-treatment-malaysia" },
          { key: "submenu.skin.eczema", fallback: "eczema-treatment-malaysia" },
          { key: "submenu.skin.keloid", fallback: "keloid-treatment-malaysia" },
          { key: "submenu.skin.rosacea", fallback: "rosacea-treatment-malaysia" },
          { key: "submenu.skin.laserHair", fallback: "laser-hair-removal-malaysia" },
          { key: "submenu.skin.tattooRemoval", fallback: "tattoo-removal-malaysia" },
          { key: "submenu.skin.chemicalPeel", fallback: "chemical-peel-malaysia" },
          { key: "submenu.skin.pigmentation", fallback: "pigmentation-treatment-malaysia" },
          { key: "submenu.skin.stretchMark", fallback: "stretch-mark-removal-malaysia" },
        ],
      },
      face: {
        label: "categories.face",
        fallback: "Face",
        items: [
          { key: "submenu.face.botox", fallback: "botox-malaysia" },
          { key: "submenu.face.cheekFiller", fallback: "cheek-filler-malaysia" },
          { key: "submenu.face.chinFiller", fallback: "chin-filler-malaysia" },
          { key: "submenu.face.dermalFiller", fallback: "dermal-filler-malaysia" },
          { key: "submenu.face.jawlineFiller", fallback: "jawline-filler-malaysia" },
          { key: "submenu.face.lipFiller", fallback: "lip-filler-malaysia" },
          { key: "submenu.face.noseFiller", fallback: "nose-filler-malaysia" },
          { key: "submenu.face.noseThread", fallback: "nose-thread-lift-malaysia" },
          { key: "submenu.face.skinBooster", fallback: "skin-booster-malaysia" },
          { key: "submenu.face.tearTrough", fallback: "tear-trough-filler-malaysia" },
          { key: "submenu.face.underEye", fallback: "under-eye-filler-malaysia" },
          { key: "submenu.face.newestML", fallback: "newest-malaysia" },
          { key: "submenu.face.profhiloML", fallback: "profhilo-malaysia" },
          { key: "submenu.face.sculptra", fallback: "sculptra-malaysia" },
          { key: "submenu.face.karisma", fallback: "karisma-malaysia" },
          { key: "submenu.face.plinest", fallback: "plinest-malaysia" },
          { key: "submenu.face.rejuran", fallback: "rejuran-malaysia" },
        ],
      },
      hair: {
        label: "categories.hair",
        fallback: "Hair",
        items: [
          { key: "submenu.hair.transplant", fallback: "hair-transplant-malaysia" },
          { key: "submenu.hair.fue", fallback: "fue-hair-transplant-malaysia" },
          { key: "submenu.hair.prp", fallback: "prp-hair-treatment-malaysia" },
          { key: "submenu.hair.lossTreatment", fallback: "hair-loss-treatment-malaysia" },
          { key: "submenu.hair.beard", fallback: "beard-transplant-malaysia" },
          { key: "submenu.hair.mesotherapy", fallback: "mesotherapy-hair-loss-malaysia" },
          { key: "submenu.hair.exosome", fallback: "exosome-hair-treatment-malaysia" },
          { key: "submenu.hair.minoxidil", fallback: "minoxidil-treatment-malaysia" },
          { key: "submenu.hair.finasteride", fallback: "finasteride-treatment-malaysia" },
        ],
      },
      regenerative: {
        label: "categories.regenerative",
        fallback: "Regenerative",
        items: [
          { key: "submenu.regenerative.testosterone", fallback: "testosterone-therapy-malaysia" },
          { key: "submenu.regenerative.ed", fallback: "ed-treatment-malaysia" },
          { key: "submenu.regenerative.hormoneReplacement", fallback: "hormone-replacement-therapy-malaysia" },
          { key: "submenu.regenerative.pcos", fallback: "pcos-treatment-malaysia" },
          { key: "submenu.regenerative.hypothyroidism", fallback: "hypothyroidism-treatment-malaysia" },
          { key: "submenu.regenerative.stemCell", fallback: "stem-cell-therapy-malaysia" },
          { key: "submenu.regenerative.antiAging", fallback: "anti-aging-therapy-malaysia" },
          { key: "submenu.regenerative.hormoneTest", fallback: "hormone-test-malaysia" },
          { key: "submenu.regenerative.menopause", fallback: "menopause-hormone-replacement-malaysia" },
          { key: "submenu.regenerative.pShot", fallback: "p-shot-malaysia" },
          { key: "submenu.regenerative.oShot", fallback: "o-shot-malaysia" },
          { key: "submenu.regenerative.shockwave", fallback: "shockwave-therapy-malaysia" },
        ],
      },
    },
  },
  { label: "nav.products", fallback: "Products", href: "/products/" },
  { label: "nav.gallery", fallback: "Gallery", href: "/gallery/" },
  { label: "nav.doctors", fallback: "Doctors", href: "/doctors/" },
  { label: "nav.blogs", fallback: "Blogs", href: "/blogs/" },
];

export const languages: Language[] = [
  { code: "EN", label: "English", flag: "🇺🇸" },
  { code: "ID", label: "Indonesia", flag: "🇮🇩" },
  { code: "MS", label: "Melayu", flag: "🇲🇾" },
  { code: "ZH", label: "中文", flag: "🇨🇳" },
  { code: "AR", label: "العربية", flag: "🇸🇦" },
];

export const categoryLabels: Record<string, { key: string; fallback: string }> = {
  weightLoss: { key: "categories.weightLoss", fallback: "Fat & Weight Loss" },
  skin: { key: "categories.skin", fallback: "Skin" },
  face: { key: "categories.face", fallback: "Face" },
  hair: { key: "categories.hair", fallback: "Hair" },
  regenerative: { key: "categories.regenerative", fallback: "Regenerative" },
};